wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1.0
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True  True  True ...  True  True  True]'
_last_obs:
  desc: null
  value: "[[ 0.          0.         -0.06447601 ...  0.          0.\n   0.       \
    \ ]\n [ 0.          0.         -0.06447601 ...  0.          0.\n   0.        ]\n\
    \ [ 0.          0.         -0.06447601 ...  0.          0.\n   0.        ]\n ...\n\
    \ [ 0.          0.         -0.06447601 ...  0.          0.\n   0.        ]\n [\
    \ 0.          0.         -0.06447601 ...  0.          0.\n   0.        ]\n [ 0.\
    \          0.         -0.06447601 ...  0.          0.\n   0.        ]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x71e4853ed540>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_stats_window_size:
  desc: null
  value: 100
_total_timesteps:
  desc: null
  value: 209715200
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1736228640
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 3
      - 16
      - 22
      - 35
      4: 3.10.12
      5: 0.12.21
      8:
      - 5
action_noise:
  desc: null
  value: NormalActionNoise
action_space:
  desc: null
  value: Box(-100.0, 100.0, (7,), float32)
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (mu): Sequential(\n    (0): Linear(in_features=30, out_features=256,\
    \ bias=True)\n    (1): ELU(alpha=1.0)\n    (2): Linear(in_features=256, out_features=256,\
    \ bias=True)\n    (3): ELU(alpha=1.0)\n    (4): Linear(in_features=256, out_features=7,\
    \ bias=True)\n    (5): Tanh()\n  )\n)"
actor_batch_norm_stats:
  desc: null
  value: '[]'
actor_batch_norm_stats_target:
  desc: null
  value: '[]'
actor_target:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (mu): Sequential(\n    (0): Linear(in_features=30, out_features=256,\
    \ bias=True)\n    (1): ELU(alpha=1.0)\n    (2): Linear(in_features=256, out_features=256,\
    \ bias=True)\n    (3): ELU(alpha=1.0)\n    (4): Linear(in_features=256, out_features=7,\
    \ bias=True)\n    (5): Tanh()\n  )\n)"
algo:
  desc: null
  value: TD3
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
clip_obs:
  desc: null
  value: 50
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=37,\
    \ out_features=256, bias=True)\n    (1): ELU(alpha=1.0)\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ELU(alpha=1.0)\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=37,\
    \ out_features=256, bias=True)\n    (1): ELU(alpha=1.0)\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ELU(alpha=1.0)\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
critic_batch_norm_stats:
  desc: null
  value: '[]'
critic_batch_norm_stats_target:
  desc: null
  value: '[]'
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=37,\
    \ out_features=256, bias=True)\n    (1): ELU(alpha=1.0)\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ELU(alpha=1.0)\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=37,\
    \ out_features=256, bias=True)\n    (1): ELU(alpha=1.0)\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ELU(alpha=1.0)\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cuda:0
env:
  desc: null
  value: <Sb3VecEnvWrapper<OrderEnforcing<ManagerBasedRLEnv<UR5e-Lift-Cube-IK>>>>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
gamma:
  desc: null
  value: 0.95
gradient_steps:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 1000
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x71e4935b0160>
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: maximize
    name: rollout/ep_rew_mean
n_envs:
  desc: null
  value: 4096
n_timesteps:
  desc: null
  value: 209715200
name:
  desc: null
  value: rel_ik_sb3_td3_ur5e_lift_cube_0_05
normalize_input:
  desc: null
  value: false
normalize_value:
  desc: null
  value: false
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box(-inf, inf, (30,), float32)
optimize_memory_usage:
  desc: null
  value: 'False'
parameters:
  desc: null
  value:
    action_noise:
      value: NormalActionNoise
    batch_size:
      values:
      - 256
      - 512
    buffer_size:
      value: 1000000
    clip_obs:
      value: 50.0
    device:
      value: cuda:0
    gamma:
      value: 0.95
    gradient_steps:
      value: 4
    learning_rate:
      values:
      - 1e-4
      - 3e-4
    learning_starts:
      value: 1000
    n_timesteps:
      value: 209715200
    normalize_input:
      value: false
    normalize_value:
      value: false
    policy:
      value: MlpPolicy
    policy_delay:
      value: 2
    policy_kwargs:
      parameters:
        activation_fn:
          values:
          - nn.ELU
          - nn.ReLU
          - nn.Tanh
        net_arch:
          value:
          - 256
          - 256
    seed:
      value: 42
    target_noise_clip:
      value: 0.5
    target_policy_noise:
      values:
      - 0.2
      - 0.4
    tau:
      value: 0.02
    train_freq:
      value: 4
policy:
  desc: null
  value: MlpPolicy
policy_class:
  desc: null
  value: <class 'stable_baselines3.td3.policies.TD3Policy'>
policy_delay:
  desc: null
  value: 2
policy_kwargs:
  desc: null
  value:
    activation_fn: nn.ELU
    net_arch:
    - 256
    - 256
program:
  desc: null
  value: train_sb3_wandb_td3.py
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x71e493568970>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 42
start_time:
  desc: null
  value: 1736228646360322889
target_noise_clip:
  desc: null
  value: 0.5
target_policy_noise:
  desc: null
  value: 0.2
tau:
  desc: null
  value: 0.02
tensorboard_log:
  desc: null
  value: runs/yh1yv5bu
train_freq:
  desc: null
  value: 4
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
