program: train_sb3_wandb.py
method: grid # bayes
name: rel_ik_sb3_ppo_ur5e_cube_lift_0_1_v3
metric:
  goal: minimize
  name: train/loss

parameters:
  seed:
    value: 42

  n_timesteps: # iteration * n_steps * nenvs: 300 * 64 * 4096 = 104857600 # 52428800 # 78643200
    value: 104857600

  policy:
    value: 'MlpPolicy'

  n_steps:
    value: 64

  batch_size:
    value: 2048

  gae_lambda:
    value: 0.95

  gamma:
    value: 0.99

  n_epochs:
    value: 8

  ent_coef: # Possibly change this to encourange more exploration
    value: 0.001

  vf_coef:
    value: 0.0001

  learning_rate:
    value: 1e-4

  clip_range:
    value: 0.2

  policy_kwargs:
    parameters:
      activation_fn: 
        values: [nn.ELU, nn.Tanh, nn.ReLU]
      net_arch:
        parameters:
          pi:
            value: [256, 128, 64]
          vf:
            value: [256, 128, 64]

  target_kl:
    value: 0.02

  max_grad_norm:
    value: 1.0

  normalize_input:
    value: True

  normalize_value:
    value: True

  clip_obs:
    value: 5