program: train_rl_games_wandb_ppo.py
method: grid
name: rel_ik_rl_games_ppo_ur5e_lift_cube_0_05_hand_e
metric:
  goal: maximize
  name: rollout/ep_rew_mean

parameters:
  seed:
    value: 42

  # Environment wrapper clipping
  env.clip_observations:
    value: 100.0
  env.clip_actions:
    value: 100.0

  algo.name:
    value: a2c_continuous

  model.name:
    value: continuous_a2c_logstd

  network.name:
    value: actor_critic
  network.separate:
    value: False
  network.space.continuous.mu_activation:
    value: None
  network.space.continuous.sigma_activation:
    value: None
  network.space.continuous.mu_init.name:
    value: default
  network.space.continuous.sigma_init.name:
    value: const_initializer
  network.space.continuous.sigma_init.val:
    value: 0
  network.space.continuous.fixed_sigma:
    value: True
  network.mlp.units:
    value: [256, 128, 64]
  network.mlp.activation:
    value: elu
  network.mlp.d2rl:
    value: False
  network.mlp.initializer.name:
    value: default
  network.mlp.regularizer.name:
    value: None

  load_checkpoint:
    value: False
  load_path:
    value: ''

  config.name:
    value: UR5e-Lift-Cube-IK
  config.env_name:
    value: rlgpu
  config.device:
    value: 'cuda:0'
  config.device_name:
    value: 'cuda:0'
  config.multi_gpu:
    value: False
  config.ppo:
    value: True
  config.mixed_precision:
    value: False
  config.normalize_input:
    value: True
  config.normalize_value:
    value: True
  config.value_bootstrap:
    value: False
  config.num_actors:
    value: 4096

  config.reward_shaper.scale_value:
    value: 0.01

  config.normalize_advantage:
    value: True
  config.gamma:
    value: 0.99
  config.tau:
    value: 0.95
  config.learning_rate:
    value: 1e-4
  config.lr_schedule:
    value: adaptive
  config.schedule_type:
    value: legacy
  config.kl_threshold:
    value: 0.01
  config.score_to_win:
    value: 100000000
  config.max_epochs:
    value: 1500
  config.save_best_after:
    value: 100
  config.save_frequency:
    value: 50
  config.print_stats:
    value: True
  config.grad_norm:
    value: 1.0
  config.entropy_coef:
    value: 0.001
  config.truncate_grads:
    value: True
  config.e_clip:
    value: 0.2
  config.horizon_length:
    value: 24
  config.minibatch_size:
    value: 98304
  config.mini_epochs:
    value: 8
  config.critic_coef:
    value: 4
  config.clip_value:
    value: True
  config.clip_actions:
    value: False
  config.seq_len:
    value: 4
  config.bounds_loss_coef:
    value: 0.0001
