# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml
program: train_sb3_wandb_td3.py
method: bayes
name: joint_pos_sb3_td3_ur5e_cube_lift
metric:
  goal: minimize
  name: train/loss

parameters:
  seed:
    value: 42

  n_timesteps: # iteration * n_steps * nenvs: 50 * 64 * 4096 = 26214400
    value: 13107200

  policy:
    value: 'MlpPolicy'

  batch_size:
    value: 256

  gamma:
    value: 0.99

  learning_rate:
    values: [1e-4, 3e-4, 1e-3]

  train_freq:
    value: 4

  gradient_steps:
    value: 4

  buffer_size: 
    value: 1000000

  policy_delay:
    value: 2

  learning_starts: 
    value: 10000

  tau: 
    value: 0.02

  target_policy_noise:
    value: 0.2

  target_noise_clip:
    value: 0.5

  policy_kwargs:
    parameters:
      # activation_fn: 
      #   value: nn.ELU
      net_arch:
        value: [400, 300]


  normalize_input:
    value: True

  normalize_value:
    value: True

  clip_obs:
    value: 5